name: Build nvidia dockerfile

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
          # relative path to the place where source code with Dockerfile is located
        context: .
        file: Dockerfile.nvidia
          # Note: tags has to be all lower-case
        tags: |
            arnoutvw/tesla_dashcam-nvidia:latest
            ghcr.io/arnoutvw/tesla_dashcam-nvidia:latest
          # build on feature branches, push only on main branch

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
